from __future__ import annotations

from typing import Protocol
from uuid import UUID


class IEnglishProvider(Protocol):
    async def authenticate(self, credentials: dict) -> bool: ...
    async def fetch_lessons(self, student_id: UUID): ...
    async def fetch_progress(self, student_id: UUID): ...
    async def sync(self, account_id: UUID): ...
