from __future__ import annotations

from typing import Protocol
from uuid import UUID


class ISchoolProvider(Protocol):
    async def authenticate(self, credentials: dict) -> bool: ...
    async def fetch_assignments(self, student_id: UUID): ...
    async def fetch_grades(self, student_id: UUID): ...
    async def sync(self, account_id: UUID): ...
